name: Run Tests

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.0'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
      run: python src/test_main.py
